---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  labels:
    app: shopfront
spec:
  type: NodePort
  selector:
    app: shopfront
  ports:
  - protocol: TCP
    port: 8010
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopfront
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: public.ecr.aws/j9z9l3h4/shopfront:latest
        imagePullPolicy: Always
        env:
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        ports:
        - containerPort: 8010
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8010
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 3
