---
apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  type: NodePort
  selector:
    app: stockmanager
  ports:
  - protocol: TCP
    port: 8030
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockmanager
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
      - name: stockmanager
        image: public.ecr.aws/j9z9l3h4/stockmanager:latest
        imagePullPolicy: Always
        env:
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        ports:
        - containerPort: 8030
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8030
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 3
